sonar.projectKey=somethingwithproof_commitkit-rust
sonar.organization=somethingwithproof

sonar.sources=src
sonar.coverage.exclusions=src/tests.rs

sonar.rust.clippyReport.reportPaths=clippy.json
sonar.rust.lcov.reportPaths=lcov.info
